CREATE TABLE Producto (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(255) NOT NULL,
    Proveedor VARCHAR(255) NOT NULL,
    Precio FLOAT(10,2) NOT NULL
);

CREATE TABLE Orden_Productos (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre VARCHAR(255) NOT NULL,
    Fecha_Emision TIMESTAMP DEFAULT CURRENT_TIMESTAMP(),
    Fecha_Entrega TIMESTAMP DEFAULT NULL,
    Servicio TEXT NOT NULL,
    Notas TEXT,
    Costo FLOAT(10,2) NOT NULL,
    Estatus ENUM('Cancelado', 'Pendiente', 'Entregado') NOT NULL DEFAULT 'Pendiente'
    Inversion FLOAT(10,2) NOT NULL DEFAULT 0.0,
);

CREATE TABLE Orden_Foto(
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    ID_Orden INT UNSIGNED NOT NULL,
    Directorio VARCHAR(255) NOT NULL,
    FOREIGN KEY (ID_Orden) REFERENCES Orden_Productos(ID)
);

CREATE TABLE Usuario (
    ID INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    Nombre_Usuario VARCHAR(255) NOT NULL,
    Contraseña VARCHAR(255) NOT NULL,
    Nombre VARCHAR(255) NOT NULL,
    Foto VARCHAR(255) NOT NULL DEFAULT 'default_user.jpg'
);